### ISSUE TITLE
[Feature] Add option to bundle the directory of server routes

### ISSUE THREAD

**Issue by rtritto** [vikejs/vike-node#35]
Routes files (eg `/server/api` directory)
```console
├── server
│   ├── index.ts         // entrypoint of server
│   ├── api              // directory for routes
│   │   ├── user
│   │   │   └── [id].ts  // GET /user/:id
```
should be bundled (during `build` script) in dist directory (eg `/dist/server/api` directory) as
```console
├── dist
│   └── server
│        ├── index.ts          // entrypoint of server
│        ├── api               // directory for routes
│        │   ├── user
│        │   │   └── [id].mjs  // GET /user/:id
```

### Solution (draft):
```ts
// vite.config.ts
import vikeNode from 'vike-node/plugin'

export default {
  // ...
  plugins: [
    vikeNode({
      entry: 'server/index.ts',
      apiDir: 'server/api'
    })
  ]
}
```
OR/AND (preferred) use `/server/api` as standard/default directory
```ts
// vite.config.ts
import vikeNode from 'vike-node/plugin'

export default {
  // ...
  plugins: [
    vikeNode({
      entry: 'server/index.ts'
    })
    // OR
    // vikeNode('server/index.ts')
  ]
}
```

**Comment by rtritto** [comment]
This feature is needed for production.
Should the priority be increased?

**Comment by rtritto** [comment]
The documentation [API Routes](https://vike.dev/api-routes) can also be updated with some references of bundle and the (recommend) usage of `vike-node` as tool:

> To create API routes, we recommend to simply use your server (such as [Express.js](https://expressjs.com/) or [Hono](https://hono.dev/)) to create new HTTP GET/POST endpoints.

FYI @brillout

**Comment by rtritto** [comment]
The feature should be added in [vike-node/src/plugin/plugins/standalonePlugin.ts](https://github.com/vikejs/vike-node/blob/bc4dad9d8f483fedbacc96f30d1337dbc0934d14/packages/vike-node/src/plugin/plugins/standalonePlugin.ts)

**Comment by brillout** [comment]
AFAICT API routes have a subpar DX compared to RPC, which is why I believe it's best for the Vike team to focus on Telefunc instead of focusing on API routes.

If you insist on using API routes, you can achieve it by implementing a new Vite plugin `vite-plugin-api-routes` (similarly to how `telefunc/vite` works). As we mentioned at https://vike.dev/api-routes we believe it's best to decouple data connection tools from Vike, that's why I'm reluctant to pursue your PR.

We'll start mentioning `vike-node`  in Vike's docs and integrating it to Bati once it's out of beta.

**Comment by rtritto** [comment]
Thanks, for the answer, now it's clearer.

In Vike's docs, it would be appropriate to add a comparison table for differences (DX, bundle size, dependencies size, performance etc) of API routes vs RPC inside Vike?

**Comment by brillout** [comment]
Although I agree it would be nice, it isn't a priority right now (there are a lot of more important things to do IMO).

**Comment by brillout** [comment]
Thank you for understanding @rtritto.

**Comment by brillout** [comment]
FYI it's actually on the radar to allow telefunctions to control caching.

In the meantime, https://vike.dev/api-routes (I just improved it https://github.com/vikejs/vike/commit/7da0ed8cd7e391edca50ca5ab6dd1a416fb67c31) mentions using Express.js and Hono routes.
