### ISSUE TITLE
server keeps restarting while running vitest when vike-node is enabled

### ISSUE THREAD

**Issue by jasonhilldm** [vikejs/vike-node#36]
I scaffolded a simple test project using bati which has express + telefunc + react and then I added vike-node and vitest. 

When running `npm run test:browser`, the server keeps restarting and the sample test doesn't run. When I comment out vikeNode in the vite config, the sample test runs fine.

I have created a repro here: https://stackblitz.com/edit/stackblitz-starters-vmcg9ih4

When running the tests in stackblitz, the server keeps restarting with the following error:

```
TypeError: Cannot read properties of undefined (reading 'get')
    at TransformPluginContext.transform (file:///home/projects/stackblitz-starters-vmcg9ih4/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:36297:50)
    at PluginContainer.transform (file:///home/projects/stackblitz-starters-vmcg9ih4/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49146:19)
    at async loadAndTransform (file:///home/projects/stackblitz-starters-vmcg9ih4/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:51978:27)
    at async instantiateModule (file:///home/projects/stackblitz-starters-vmcg9ih4/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:52923:44) {
  plugin: 'vite:css-post',
  id: '/home/projects/stackblitz-starters-vmcg9ih4/layouts/style.css'
}
┌─────────────────────────────────────────────────────────────────────────────┐
│ The error could be a CJS/ESM issue, see https://vike.dev/broken-npm-package │
└─────────────────────────────────────────────────────────────────────────────┘
```

I am not seeing any errors in the console when running locally, but the server does keep restarting, so I am not sure if the above error is just something to do with stackblitz environment.

When I comment out vikeNode in the vite config locally then the sample test runs fine. When I do that in stackblitz though, the server does start and the vitest dashboard is displayed, but no tests are found or run. Again, not sure if this is something specific to stackblitz that I don't have quite right.

**Comment by brillout** [comment]
Can you publish the repro on GitHub?

@magne4000 Ideas? Let me know if you don't have the bandwidth to have a look at this and I'll take care of it.

**Comment by magne4000** [comment]
@brillout I have a few ideas yes. Let me check

**Comment by magne4000** [comment]
vitedev seems to also hijack the vite devserver while running tests in browser mode, thus conflicting with `vike-node`.
A quick workaround is to disable the `vike-node` devserver plugin when `mode === 'test'`.
I'm not sure that we can manage to make both `vike-node` and vitedev work in tandem.

**Comment by brillout** [comment]
I personally use Vitest only for unit tests, so I ain't sure how using Vitest for end-to-end tests works.

I guess we have to somehow signal Vitest that the server has changed and that all tests should be re-run? Does Vitest has an API for that?

Ideally we should revert https://github.com/vikejs/vike-node/pull/37 and implement a proper Vitest end-to-end integration.

**Comment by magne4000** [comment]
@jasonhilldm latest version of `vike-node` should not conflict with vitest any longer.

**Comment by jasonhilldm** [comment]
Thanks - I can confirm that the issue with the server restarting is now fixed.
